apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: imperio-instances
  name: imperio-instances
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imperio-instances
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: imperio-instances
    spec:
      containers:
        - image: finda/imperio-instances
          imagePullPolicy: Always
          name: imperio-instances
          ports:
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: imperio-instances
spec:
  ports:
    - port: 9001
      name: http
  selector:
    app: imperio-instances
---
