apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: imperio-instances
  name: imperio-instances
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imperio-instances
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: imperio-instances
    spec:
      containers:
        - image: finda/imperio-instances
          imagePullPolicy: Always
          name: imperio-instances
          ports:
            - containerPort: 80
          env:
            - name: pg_pass
              valueFrom:
                secretKeyRef:
                  name: data-imperio-postgresql
                  key: postgres-password
            - name: pg_user
              value: postgres
            - name: pg_ip
              value: POSTGRES_IP_SED
            - name: tls_pass
              valueFrom:
                secretKeyRef:
                  name: imperio-store
                  key: spring
            - name: linode_token
              valueFrom:
                secretKeyRef:
                  name: linode-token
                  key: linode-token
---
apiVersion: v1
kind: Service
metadata:
  name: imperio-instances
spec:
  ports:
    - port: 8000
      targetPort: 80
      name: http
  selector:
    app: imperio-instances
---

